#!/usr/bin/env python

import SimpleHTTPServer
import SocketServer

PORT = 8000

Handler = SimpleHTTPServer.SimpleHTTPRequestHandler

httpd = SocketServer.TCPServer(("", PORT), Handler)

print "open browser to http://localhost:" + str(PORT)
httpd.serve_forever()
